version: "3.9"
services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cmsdb

  smtp:
    image: "gessnerfl/fake-smtp-server"
    ports:
      - "5025:5025"
      - "5080:5080"
      - "5081:5081"