version: "3.9"
services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cmsdb
  smtp:
    image: "gessnerfl/fake-smtp-server"
    ports:
      - "5025:5025"
      - "5080:5080"
      - "5081:5081"
  backend:
    image: "pai-cms-backend"
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/cmsdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: ;L9$L/8igYk!t/wxT2cAx]jPr3F6uvg?jaZ(Vqua{:DECEzny{H:(Ayw3HmA@C;m3e%V#_K+%-eE4g(c5V&R.&qEDmf$rZ)Hy6K4?iariZ5gp.Jp.ddg8a.M}4+8M75W(awQve#B!DaVrA3b=#/AFP
      ACCESS_TOKEN_EXPIRATION: 900000
      REFRESH_TOKEN_EXPIRATION: 9000000
      RESET_TOKEN_EXPIRATION: 600000
      SHARED_CONTENT_MAX_TOKEN_EXPIRATION: 365
      MAIL_HOST: smtp
      MAIL_PORT: 5025
      MAIL_USERNAME: no-reply@cms-backend.com
      MAIL_PASSWORD: password
      FORGOTTEN_PASSWORD_URL: http://localhost:4200/forgotten-password
  frontend:
    image: "cms-frontend"
    ports:
      - "4200:4200"